Fiap06.Web.MVC/Fiap06.Web.MVC/Models/Animal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Fiap06.Web.MVC.Models
{
    [Table("TAnimal")]
    public class Animal
    {                
        [Column("Id")]
        public int AnimalId { get; set; }

        [Required]
        [MaxLength(100)]
        public string Nome { get; set; }

        public string Raca { get; set; }

        public bool Castrado { get; set; }

        public float Peso { get; set; }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap06.Web.MVC.Models
{
    public class Produto
    {
        public int ProdutoId { get; set; }
        public string Nome { get; set; }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Controllers/AnimalController.cs
using Fiap06.Web.MVC.Models;
using Fiap06.Web.MVC.Persistencia;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap06.Web.MVC.Controllers
{
    public class AnimalController : Controller
    {
        private PetshopContext _context = new PetshopContext();

        [HttpGet]
        public ActionResult Pesquisar(string nome)
        {
            var lista = _context.Animais
                .Where(a => a.Nome.Contains(nome)).ToList();
            return View("Listar", lista);
        }
        [HttpPost]
        public ActionResult Excluir(int id)
        {
            var animal = _context.Animais.Find(id);
            _context.Animais.Remove(animal);
            _context.SaveChanges();
            TempData["msg"] = "Animal excluído";
            return RedirectToAction("Listar");
        }

        [HttpPost]
        public ActionResult Alterar(Animal animal)
        {
            _context.Entry(animal).State = EntityState.Modified;
            _context.SaveChanges();
            TempData["msg"] = "Animal atualizado!";
            return RedirectToAction("Listar");
        }

        [HttpGet]
        public ActionResult Alterar(int id)
        {
            //buscar o animal no banco de dados
            var animal = _context.Animais.Find(id);
            //retorna a página com os dados do animal
            return View(animal);
        }

        [HttpGet]
        public ActionResult Listar()
        {
            //Recupera os animais cadastrados no banco 
            var lista = _context.Animais.ToList();
            //Retorna a tela com a lista de animais
            return View(lista);
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Animal animal)
        {
            _context.Animais.Add(animal);
            _context.SaveChanges();
            TempData["msg"] = "Cadastrado com sucesso!";
            return RedirectToAction("Cadastrar");
        }

    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap06.Web.MVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Animal/Alterar.cshtml
@model Fiap06.Web.MVC.Models.Animal
@{
    ViewBag.Title = "Alterar";
}

<h2>Alterar</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(a => a.AnimalId)
    <div class="form-group">
        @Html.LabelFor(a => a.Nome)
        @Html.TextBoxFor(a => a.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.Raca)
        @Html.TextBoxFor(a => a.Raca, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.Peso)
        @Html.TextBoxFor(a => a.Peso, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(a => a.Castrado)
        @Html.LabelFor(a => a.Castrado)
    </div>
    <input type="submit" value="Editar" class="btn btn-primary" />
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Animal/Cadastrar.cshtml
@model Fiap06.Web.MVC.Models.Animal
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(a => a.Nome)
        @Html.TextBoxFor(a => a.Nome, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.Peso)
        @Html.TextBoxFor(a => a.Peso, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(a => a.Raca)
        @Html.TextBoxFor(a => a.Raca, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(a => a.Castrado)
        @Html.LabelFor(a => a.Castrado)
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary" />
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Animal/Listar.cshtml
@model List<Fiap06.Web.MVC.Models.Animal>

@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

@if (TempData["msg"] != null)
{
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
}
@using (Html.BeginForm("Pesquisar", "Animal", FormMethod.Get, new { @class = "form-inline" }))
{
    @Html.TextBox("Nome", null, new { @class = "form-control", placeholder = "Digite um nome" })
    <input type="submit" value="Pesquisar" class="btn btn-primary" />
}
<table class="table table-striped">
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Peso</th>
        <th>Raça</th>
        <th>Castrado</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.AnimalId</td>
            <td>@item.Nome</td>
            <td>@item.Peso</td>
            <td>@item.Raca</td>
            <td>@(item.Castrado ? "Sim" : "Não")</td>
            <td>
                @Html.ActionLink("Editar", "Alterar", new { id = item.AnimalId },
               new { @class = "btn btn-info btn-xs" })
                <button onclick="codigoAnimal.value = @item.AnimalId" type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#myModal">
                    Excluir
                </button>
            </td>
        </tr>
    }
</table>
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmação</h4>
      </div>
      <div class="modal-body">
        Deseja excluir o animal?
      </div>
      <div class="modal-footer">
          @using (Html.BeginForm("Excluir", "Animal"))
          {
              <input type="hidden" name="id" id="codigoAnimal" />
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Excluir</button>
          }

      </div>
    </div>
  </div>
</div>

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@section scripts{
    <p>Conteúdo adicionado no final do Layout</p>
}

Fiap06.Web.MVC/Fiap06.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PetShop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastrar Animal","Cadastrar","Animal")</li>
                    <li>@Html.ActionLink("Animais","Listar","Animal")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!--Local para as páginas adicionarem conteúdo no Layout-->
    @RenderSection("scripts",false)
</body>
</html>