04.Fiap.Web.MVC/04.Fiap.Web.MVC/Models/Medico.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _04.Fiap.Web.MVC.Models
{
    public class Medico
    {
        public int Crm { get; set; }
        public String Nome { get; set; }
        public bool Ativo { get; set; }
        public string Descricao { get; set; }
        public decimal Salario { get; set; }
    }
}

04.Fiap.Web.MVC/04.Fiap.Web.MVC/Controllers/MedicoController.cs
using _04.Fiap.Web.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _04.Fiap.Web.MVC.Controllers
{
    public class MedicoController : Controller
    {
        private static List<Medico> _banco = new List<Medico>();

        [HttpGet]
        public ActionResult Listar()
        {
            return View(_banco);
        }
        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(Medico medico)
        {
            _banco.Add(medico);
            TempData["msg"] = "Médico cadastrado!";
            return RedirectToAction("Cadastrar");
        }
    }
}

04.Fiap.Web.MVC/04.Fiap.Web.MVC/Views/Medico/Cadastrar.cshtml
@model _04.Fiap.Web.MVC.Models.Medico

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>
    @if(TempData["msg"] != null)
    {
    <div class="alert alert-success">
        @TempData["msg"]
    </div>
    }

@using (Html.BeginForm())
{

    <div class="form-group">
        @Html.LabelFor(pipoca => pipoca.Crm)
        @Html.TextBoxFor(m => m.Crm)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Nome)
        @Html.TextBoxFor(m => m.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Salario)
        @Html.TextBoxFor(m => m.Salario)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Descricao)
        @Html.TextAreaFor(m => m.Descricao)
    </div>
    <div class="form-group">
        @Html.CheckBoxFor(m => m.Ativo)
        @Html.LabelFor(m => m.Ativo)
    </div>
    <input type="submit" value="Cadastrar" class="btn btn-primary"/>
}

04.Fiap.Web.MVC/04.Fiap.Web.MVC/Views/Medico/Listar.cshtml
@model List<_04.Fiap.Web.MVC.Models.Medico>
@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<table class="table">
    <tr>
        <th>CRM</th>
        <th>Nome</th>
        <th>Salário</th>
        <th>Ativo</th>
        <th>Descrição</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Crm</td>
            <td>@item.Nome</td>
            <td>@item.Salario</td>
            <td>@(item.Ativo?"Ativo":"Inativo")</td>
            <td>@item.Descricao</td>
        </tr>
    }
</table>

04.Fiap.Web.MVC/04.Fiap.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FIAP Hell", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastrar Médico","Cadastrar","Medico")</li>
                    <li>@Html.ActionLink("Listar Médicos","Listar","Medico")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>